[2024-05-11T03:25:36.036+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T03:25:36.047+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.store_user manual__2024-05-11T03:25:28.914838+00:00 [queued]>
[2024-05-11T03:25:36.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.store_user manual__2024-05-11T03:25:28.914838+00:00 [queued]>
[2024-05-11T03:25:36.054+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-11T03:25:36.064+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_user> on 2024-05-11 03:25:28.914838+00:00
[2024-05-11T03:25:36.069+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=323) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-11T03:25:36.070+0000] {standard_task_runner.py:63} INFO - Started process 325 to run task
[2024-05-11T03:25:36.069+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2024-05-11T03:25:28.914838+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpnc64d498']
[2024-05-11T03:25:36.071+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask store_user
[2024-05-11T03:25:36.099+0000] {task_command.py:426} INFO - Running <TaskInstance: user_processing.store_user manual__2024-05-11T03:25:28.914838+00:00 [running]> on host cfc7b97c1618
[2024-05-11T03:25:36.159+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='store_user' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T03:25:28.914838+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T03:25:28.914838+00:00'
[2024-05-11T03:25:36.160+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-11T03:25:36.168+0000] {postgres.py:175} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2024-05-11T03:25:36.174+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-05-11T03:25:36.179+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-11T03:25:36.180+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-11T03:25:36.186+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, run_id=manual__2024-05-11T03:25:28.914838+00:00, execution_date=20240511T032528, start_date=20240511T032536, end_date=20240511T032536
[2024-05-11T03:25:36.203+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-11T03:25:36.215+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-11T03:25:36.217+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
